// <auto-generated />
using HotelListing.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelListing.API.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Nigeria",
                            ShortName = "NGA"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Mamlaka Saudiyya",
                            ShortName = "KSA"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "United Arab Emirate",
                            ShortName = "UAE"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Plot 445,Ozumba Mbadiwe,Victoria Island, Lagos.",
                            CountryId = 1,
                            Name = "Oriental Hotel",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "6623 Al Shohadaa Eastern Ring Road, Riyadh.",
                            CountryId = 2,
                            Name = "Hilton Riyadh Hotel",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Al Mustaqbal St - opposite The Dubai Mall - Trade Centre - Dubai",
                            CountryId = 3,
                            Name = "Swissôtel Al Murooj Dubai",
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("HotelListing.API.Models.Hotel", b =>
                {
                    b.HasOne("HotelListing.API.Models.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.API.Models.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
